version: '{build}'
environment:
  matrix:
    - nodejs_version: '4'
    - nodejs_version: '6'
    - nodejs_version: '8'
branches:
  only:
    - master
    - /^greenkeeper.*$/
install:
  - ps: Install-Product node $env:nodejs_version
  - IF %nodejs_version% LSS 5 npm -g install npm@5.3
  - appveyor-retry npm install
platform:
  - x86
  - x64
test_script:
  - npm run test
build: off
deploy: off
